### ISSUE TITLE
[Fullstack] Test announcements

### ISSUE THREAD

**Issue by dpang314** [GTBitsOfGood/Healing4Heroes#101]
### Description
* We need to verify that admins can create announcements and users receive them
* There won't be a PR for this ticket. Instead, leave a comment with the cases you tested and any bugs you encountered

### Acceptance Criteria
- [ ] Admins can't send empty announcements
- [ ] Users can view sent announcements
- [ ] Read/unread announcements are updated properly in the user list

### Other Notes
* Try a variety of inputs and edge cases

**Comment by ygupta17** [comment]
Passed Tests: 
- Admin cannot send empty announcements
- Read/unread announcements are updated properly in user list
- Users can view sent announcements

Failed Tests:
- If I input spaces in the description and title field, it does not give an error
