### ISSUE TITLE
[Backend] Set Firebase user email verification status

### ISSUE THREAD

**Issue by dpang314** [GTBitsOfGood/Healing4Heroes#66]
### Description
* When a user is created their email is not verified. 
* This is reflected in MongoDB, but not hasn't been implemented with Firebase, which we use for authentication.

### Acceptance Criteria
- [x] In `/api/user/user` `POST` when a user is created update associated Firebase user to have `emailVerified: false`
- [x] in `/api/auth/verify` `PATCH` on a successful verification, update the Firebase user to have `emailVerified: true`
- [x] in `firebase_storage_rules.txt` restrict both read and write to require `request.auth.emailVerified` to be true

### Other Notes
* https://firebase.google.com/docs/auth/admin/manage-users#update_a_user
* https://firebase.google.com/docs/rules/rules-and-auth
* https://firebase.google.com/docs/rules/rules-language#storage

**Comment by thanasis457** [comment]
In Firebase, `emailVerified: false` is the default configuration if verified status is not provided. Either way I added some code to ensure that is is set to `false` for new users.
