### ISSUE TITLE
[Fullstack] Test Analytics Dashboard

### ISSUE THREAD

**Issue by dpang314** [GTBitsOfGood/Healing4Heroes#97]
### Description
* We need to verify that the analytics dashboard functions as intended
* There won't be a PR for this ticket. Instead, leave a comment with the cases you tested and any bugs you encountered

### Acceptance Criteria
- [x] Analytics dashboard displays information properly
- [x] Analytics dashboard data is updated correctly (e.g. when creating a user, adding a log, etc.)
- [x] Analytics dashboard still functions when first initialized (e.g. no negative behavior data, make sure we aren't dividing by 0 anywhere)
- [ ] Test navigating to specific users and viewing their data
- [x] These are just examples of tests, make sure to try more cases

### Other Notes
* Try a variety of inputs and edge cases
* It may help to use a local testing database to test initialization

**Comment by jsn-li** [comment]
## Backend tests using postman:
- increment total users when a user gets verified
- decrement total users when a verified user gets deleted
- do not decrement total users when a non-verified user gets deleted
- increment users completed training when an animal gets updated from below 800 hours to >= 800 hours.
- do not increment users completed training when an animal gets updated but hours do not increase past 800 hours
- do not increment users completed training when an animal gets updated but the animal was already past 800 hours
- cumulative training hours increases when a new training log is added
- active users updates when new user adds training log

## Frontend tests:
- dashboard displays proper data
- opening dashboard triggers initialization when the analytics object does not yet exist; then, it displays properly
- increment total users when a user gets verified
- cumulative training hours increases when a new training log is added
- negative behavior logs updates properly when dashboard is opened
- increment users completed training after creating a training log that pushes total hours from below 800 hours to >= 800 hours.

## Failed tests:
- opening dashboard when there are 0 total users
   - It looks like the "users who completed training" graph breaks. maybe dividing by 0?

**Comment by jsn-li** [comment]
There's also a bug with the fonts, it shows this error every time:
<img width="773" alt="Screen Shot 2023-03-17 at 1 48 25 PM" src="https://user-images.githubusercontent.com/21373185/225986267-a34f0f0d-f09e-4b6c-821a-2b71fb56c4cf.png">

Nothing breaks or anything though.
