### ISSUE TITLE
[Fullstack] Test admin user lists

### ISSUE THREAD

**Issue by dpang314** [GTBitsOfGood/Healing4Heroes#98]
### Description
* We need to verify that the admin dashboard user lists function as intended
* This includes: "View All Users," "View Admin Users," "New User Verification Portal," and "Users with 800 hours"
* There won't be a PR for this ticket. Instead, leave a comment with the cases you tested and any bugs you encountered

### Acceptance Criteria
- [x] User lists display correct users
- [x] Verifying new users functions properly
- [x] Users with 800 hours functions updates when users reach 800 hours
- [x] These are just examples of tests, make sure to try more cases

### Other Notes
* Try a variety of inputs and edge cases
* You should be creating new normal users for testing

**Comment by thanasis457** [comment]
- Tested viewing "All Users" works as expected but search bar does not work. There is no button to filter the results.
- New user verification works properly. Tested every stage of new user registration and the database gets updated correctly accordingly.
- "View Admin Users" correctly displays all admin users
- "New User Verification Portal" works as expected and the database gets updated correctly too.
- "Users with 800 hours" works as expected and updates correctly.
- Problem on all options on the Admin Dashboard: Every page like "View All Users" or "Users with 800 hours" show the title "All Users" regardless of the page. Maybe we want to change this to reflect the page we are currently at.

Everything was tested using the API as the source of the "correct data" to make sure the pages show all information correctly.
