### ISSUE TITLE
[Fullstack] Test creating user accounts/resetting password

### ISSUE THREAD

**Issue by dpang314** [GTBitsOfGood/Healing4Heroes#99]
### Description
* We need to verify that the creating user accounts and resetting passwords function properly
* There won't be a PR for this ticket. Instead, leave a comment with the cases you tested and any bugs you encountered

### Acceptance Criteria
- [ ] Can't sign up with existing email
- [ ] Able to upload images
- [ ] Confirmation emails are delivered
- [ ] These are just examples of tests, make sure to try more cases

### Other Notes
* Try a variety of inputs and edge cases
* Make sure you ensure that permissions are limited prior to admin verification

**Comment by bat-kryptonyte** [comment]
- Tested upload image function, user is able to successfully upload image.
- Tested sign up with existing email, have warning message on mobile end but no warning message on web-end (not necessary anyways)
- confirmation email shows preview but not sending (dev mode)

**Comment by bat-kryptonyte** [comment]
**Tests**
Functionally successful tests are denoted with a checkmark. Permissions are limited prior to admin verification.

- [x]  Sign up with existing email 
         - Tried signup with existing email but non-matching password, password error message appears before checking 
            duplicate email warning message
- [x]  Login with non-existent email (Cannot login but no warning message)
- [ ]  **Tested existing email sign up (Warning message for email already in-use) but cannot login or password reset (could 
        not find user with email)**
- [x]  Tested sending confirmation emails for resetting password, email won't send in dev mode, but confirmation 
         code from previews are successful -> jumps to the reset password screen
- [x] Verification code fields do not clear after verification request expires, has to clear each cell one by one manually.
- [ ] Dog birthday can be set prior to the user's birthday (I guess this is fine)
- [x] Upload image generally works, cannot upload video, but uploading a large image file (i.e. RAW format or 8k resolution) 
       crashes the app
